os: osx
osx_image: xcode11.3
language: swift
script: xcodebuild clean build test -project UnitTests/UnitTests.xcodeproj -scheme "UnitTests" -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=13.0,name=iPhone 8' ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO