os: osx
osx_image: xcode13.4
language: swift
script: xcodebuild clean build test -project UnitTests.xcodeproj -scheme "UnitTests" -destination 'platform=iOS Simulator,name=iPhone 11' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
