name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-tests:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2

    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_14.0.app
      
    - name: Xcode version
      run: /usr/bin/xcodebuild -version

    - name: Build and test
      run: xcodebuild clean build test -project UnitTests.xcodeproj -scheme "UnitTests" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 14,OS=16.0" ONLY_ACTIVE_ARCH=YES